spring:
  application:
    name: producer
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      sqs:
        endpoint: ${SQS_ENDPOINT:http://localhost:4566}

aws:
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL}
